name: 'dbt_adventure_works'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_adventure_works:
    # Global configuration (by default, everything is a view)
    +materialized: view  

    # Specific configurations by business domain
    person:
      staging:
        +materialized: view  # Person Staging as view
      intermediate:
        +materialized: view  # Person Intermediate as view
      marts:
        +materialized: table  # Person Marts as table

    production:
      staging:
        +materialized: view  # Production Staging as view
      intermediate:
        +materialized: view  # Production Intermediate as view
      marts:
        +materialized: table  # Production Marts as table

    sales:
      staging:
        +materialized: view  # Sales Staging as view
      intermediate:
        +materialized: view  # Sales Intermediate as view
      marts:
        +materialized: table  # Sales Marts as table
