name: 'dbt_adventure_works'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_adventure_works:
    # Configuração global (por padrão, tudo é uma view)
    +materialized: view  

    # Configurações específicas por domínio de negócio
    person:
      staging:
        +materialized: view  # Person Staging como view
      intermediate:
        +materialized: view  # Person Intermediate como view
      marts:
        +materialized: table  # Person Marts como tabela

    production:
      staging:
        +materialized: view  # Production Staging como view
      intermediate:
        +materialized: view  # Production Intermediate como view
      marts:
        +materialized: table  # Production Marts como tabela

    sales:
      staging:
        +materialized: view  # Sales Staging como view
      intermediate:
        +materialized: view  # Sales Intermediate como view
      marts:
        +materialized: table  # Sales Marts como tabela
